import { SiteConfig } from "@/types";

import { absoluteUrl } from "@/lib/utils";

export const siteConfig: SiteConfig = {
  name: "Quasar",
  title: "Quasar: Explore Our Thoughts, Stories and Ideas",
  description:
    "A community-driven platform sharing captivating stories that impact on our lives, careers, and the world.",
  url: absoluteUrl(),
  ogImage: absoluteUrl("/og.jpg"),
  creator: "@ikyawthetpaing",
  authors: [
    { name: "Kyaw Thet Paing", url: "https://ikyawthetpaing.vercel.app" },
  ],
  keywords: [
    "quasar",

    "travel blogs",
    "adventure",
    "exploration",
    "wanderlust",
    "destination guides",
    "travel tips",
    "cultural experiences",
    "vacation planning",
    "off the beaten path",

    "art insights",
    "fine arts",
    "contemporary art",
    "artistic expression",
    "art galleries",
    "art exhibitions",
    "creative process",
    "artistic inspiration",
    "visual arts",
    "art critique",

    "fashion trends",
    "style inspiration",
    "clothing design",
    "fashionistas",
    "haute couture",
    "street style",
    "fashion accessories",
    "seasonal fashion",
    "sustainable fashion",
    "celebrity fashion",

    "lifestyle choices",
    "wellness",
    "self-improvement",
    "personal development",
    "daily routines",
    "mindfulness",
    "healthy habits",
    "work-life balance",
    "hobbies",
    "stress management",

    "culinary delights",
    "foodie adventures",
    "gastronomy",
    "cooking tips",
    "food photography",
    "restaurant reviews",
    "ethnic cuisines",
    "food trends",
    "healthy recipes",
    "indulgent treats",

    "technology news",
    "innovation",
    "gadgets",
    "digital trends",
    "coding",
    "software development",
    "tech reviews",
    "startups",
    "future tech",
    "emerging technologies",

    "wellness",
    "fitness tips",
    "mental health",
    "nutrition",
    "holistic health",
    "medical breakthroughs",
    "healthy living",
    "mind-body connection",
    "preventive healthcare",
    "well-being",

    "scientific discoveries",
    "research updates",
    "space exploration",
    "environmental science",
    "biology",
    "physics",
    "chemistry",
    "scientific breakthroughs",
    "science communication",
    "innovations in science",
  ],
};
